//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENumberClient.ENIdentificationServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ENIdentificationServiceRef.IENIdentificationService")]
    public interface IENIdentificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENIdentificationService/VerifyENumber", ReplyAction="http://tempuri.org/IENIdentificationService/VerifyENumberResponse")]
        bool VerifyENumber(string eNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENIdentificationService/VerifyENumber", ReplyAction="http://tempuri.org/IENIdentificationService/VerifyENumberResponse")]
        System.Threading.Tasks.Task<bool> VerifyENumberAsync(string eNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IENIdentificationServiceChannel : ENumberClient.ENIdentificationServiceRef.IENIdentificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ENIdentificationServiceClient : System.ServiceModel.ClientBase<ENumberClient.ENIdentificationServiceRef.IENIdentificationService>, ENumberClient.ENIdentificationServiceRef.IENIdentificationService {
        
        public ENIdentificationServiceClient() {
        }
        
        public ENIdentificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ENIdentificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ENIdentificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ENIdentificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool VerifyENumber(string eNumber) {
            return base.Channel.VerifyENumber(eNumber);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyENumberAsync(string eNumber) {
            return base.Channel.VerifyENumberAsync(eNumber);
        }
    }
}
