//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENumberClient.EvaluationServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EvaluationServiceRef.IEvaluationService")]
    public interface IEvaluationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluationService/EvaluateQueryResult", ReplyAction="http://tempuri.org/IEvaluationService/EvaluateQueryResultResponse")]
        string EvaluateQueryResult(string queryResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluationService/EvaluateQueryResult", ReplyAction="http://tempuri.org/IEvaluationService/EvaluateQueryResultResponse")]
        System.Threading.Tasks.Task<string> EvaluateQueryResultAsync(string queryResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEvaluationServiceChannel : ENumberClient.EvaluationServiceRef.IEvaluationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvaluationServiceClient : System.ServiceModel.ClientBase<ENumberClient.EvaluationServiceRef.IEvaluationService>, ENumberClient.EvaluationServiceRef.IEvaluationService {
        
        public EvaluationServiceClient() {
        }
        
        public EvaluationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EvaluationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvaluationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvaluationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EvaluateQueryResult(string queryResult) {
            return base.Channel.EvaluateQueryResult(queryResult);
        }
        
        public System.Threading.Tasks.Task<string> EvaluateQueryResultAsync(string queryResult) {
            return base.Channel.EvaluateQueryResultAsync(queryResult);
        }
    }
}
